// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230210121452_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            Name = "Spencer",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Name = "Max",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Name = "Marlowe",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            Name = "Bubba",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 3,
                            Name = "Charlie",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 7,
                            Name = "Sammy",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 9,
                            Name = "Mango",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 3,
                            Name = "Jewel",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 7,
                            Name = "Bobby",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
